package scut218.pisces.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgProtocol.proto

public final class MsgProtocol {
  private MsgProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface msgProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msgProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *要第一个set
     * </pre>
     *
     * <code>string time = 1;</code>
     */
    String getTime();
    /**
     * <pre>
     *要第一个set
     * </pre>
     *
     * <code>string time = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>int64 id = 2;</code>
     */
    long getId();

    /**
     * <code>string fromWhom = 3;</code>
     */
    String getFromWhom();
    /**
     * <code>string fromWhom = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromWhomBytes();

    /**
     * <code>string toWhom = 4;</code>
     */
    String getToWhom();
    /**
     * <code>string toWhom = 4;</code>
     */
    com.google.protobuf.ByteString
        getToWhomBytes();

    /**
     * <code>.msgProtocol.Type type = 5;</code>
     */
    int getTypeValue();
    /**
     * <code>.msgProtocol.Type type = 5;</code>
     */
    msgProtocol.Type getType();

    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    java.util.List<msgProtocol.msgDetail>
        getMsgDList();
    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    msgProtocol.msgDetail getMsgD(int index);
    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    int getMsgDCount();
    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    java.util.List<? extends msgProtocol.msgDetailOrBuilder>
        getMsgDOrBuilderList();
    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    msgProtocol.msgDetailOrBuilder getMsgDOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code msgProtocol}
   */
  public  static final class msgProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msgProtocol)
      msgProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use msgProtocol.newBuilder() to construct.
    private msgProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private msgProtocol() {
      time_ = "";
      id_ = 0L;
      fromWhom_ = "";
      toWhom_ = "";
      type_ = 0;
      msgD_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private msgProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              time_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              fromWhom_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              toWhom_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                msgD_ = new java.util.ArrayList<msgDetail>();
                mutable_bitField0_ |= 0x00000020;
              }
              msgD_.add(
                  input.readMessage(msgDetail.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          msgD_ = java.util.Collections.unmodifiableList(msgD_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgProtocol.internal_static_msgProtocol_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgProtocol.internal_static_msgProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              msgProtocol.class, Builder.class);
    }

    /**
     * Protobuf enum {@code msgProtocol.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOMENT = 0;</code>
       */
      MOMENT(0),
      /**
       * <code>COMMENT = 1;</code>
       */
      COMMENT(1),
      /**
       * <code>FUNREQ = 2;</code>
       */
      FUNREQ(2),
      /**
       * <code>OTHERS = 3;</code>
       */
      OTHERS(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MOMENT = 0;</code>
       */
      public static final int MOMENT_VALUE = 0;
      /**
       * <code>COMMENT = 1;</code>
       */
      public static final int COMMENT_VALUE = 1;
      /**
       * <code>FUNREQ = 2;</code>
       */
      public static final int FUNREQ_VALUE = 2;
      /**
       * <code>OTHERS = 3;</code>
       */
      public static final int OTHERS_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return MOMENT;
          case 1: return COMMENT;
          case 2: return FUNREQ;
          case 3: return OTHERS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return msgProtocol.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:msgProtocol.Type)
    }

    /**
     * Protobuf enum {@code msgProtocol.msgType}
     */
    public enum msgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *文字
       * </pre>
       *
       * <code>TEXT = 0;</code>
       */
      TEXT(0),
      /**
       * <pre>
       *图片
       * </pre>
       *
       * <code>IMAGE = 1;</code>
       */
      IMAGE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *文字
       * </pre>
       *
       * <code>TEXT = 0;</code>
       */
      public static final int TEXT_VALUE = 0;
      /**
       * <pre>
       *图片
       * </pre>
       *
       * <code>IMAGE = 1;</code>
       */
      public static final int IMAGE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static msgType valueOf(int value) {
        return forNumber(value);
      }

      public static msgType forNumber(int value) {
        switch (value) {
          case 0: return TEXT;
          case 1: return IMAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<msgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          msgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<msgType>() {
              public msgType findValueByNumber(int number) {
                return msgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return msgProtocol.getDescriptor().getEnumTypes().get(1);
      }

      private static final msgType[] VALUES = values();

      public static msgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private msgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:msgProtocol.msgType)
    }

    public interface msgDetailOrBuilder extends
        // @@protoc_insertion_point(interface_extends:msgProtocol.msgDetail)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.msgProtocol.msgType Type = 1;</code>
       */
      int getTypeValue();
      /**
       * <code>.msgProtocol.msgType Type = 1;</code>
       */
      msgType getType();

      /**
       * <code>string msgName = 2;</code>
       */
      String getMsgName();
      /**
       * <code>string msgName = 2;</code>
       */
      com.google.protobuf.ByteString
          getMsgNameBytes();

      /**
       * <code>bytes msgStream = 3;</code>
       */
      com.google.protobuf.ByteString getMsgStream();
    }
    /**
     * Protobuf type {@code msgProtocol.msgDetail}
     */
    public  static final class msgDetail extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:msgProtocol.msgDetail)
        msgDetailOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use msgDetail.newBuilder() to construct.
      private msgDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private msgDetail() {
        type_ = 0;
        msgName_ = "";
        msgStream_ = com.google.protobuf.ByteString.EMPTY;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private msgDetail(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                msgName_ = s;
                break;
              }
              case 26: {

                msgStream_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgProtocol.internal_static_msgProtocol_msgDetail_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgProtocol.internal_static_msgProtocol_msgDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                msgDetail.class, Builder.class);
      }

      public static final int TYPE_FIELD_NUMBER = 1;
      private int type_;
      /**
       * <code>.msgProtocol.msgType Type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.msgProtocol.msgType Type = 1;</code>
       */
      public msgType getType() {
        msgType result = msgType.valueOf(type_);
        return result == null ? msgType.UNRECOGNIZED : result;
      }

      public static final int MSGNAME_FIELD_NUMBER = 2;
      private volatile Object msgName_;
      /**
       * <code>string msgName = 2;</code>
       */
      public String getMsgName() {
        Object ref = msgName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgName_ = s;
          return s;
        }
      }
      /**
       * <code>string msgName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgNameBytes() {
        Object ref = msgName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MSGSTREAM_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString msgStream_;
      /**
       * <code>bytes msgStream = 3;</code>
       */
      public com.google.protobuf.ByteString getMsgStream() {
        return msgStream_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (type_ != msgType.TEXT.getNumber()) {
          output.writeEnum(1, type_);
        }
        if (!getMsgNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgName_);
        }
        if (!msgStream_.isEmpty()) {
          output.writeBytes(3, msgStream_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (type_ != msgType.TEXT.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_);
        }
        if (!getMsgNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgName_);
        }
        if (!msgStream_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, msgStream_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof msgDetail)) {
          return super.equals(obj);
        }
        msgDetail other = (msgDetail) obj;

        boolean result = true;
        result = result && type_ == other.type_;
        result = result && getMsgName()
            .equals(other.getMsgName());
        result = result && getMsgStream()
            .equals(other.getMsgStream());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (37 * hash) + MSGNAME_FIELD_NUMBER;
        hash = (53 * hash) + getMsgName().hashCode();
        hash = (37 * hash) + MSGSTREAM_FIELD_NUMBER;
        hash = (53 * hash) + getMsgStream().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static msgDetail parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static msgDetail parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static msgDetail parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static msgDetail parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static msgDetail parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static msgDetail parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static msgDetail parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static msgDetail parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static msgDetail parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static msgDetail parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static msgDetail parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static msgDetail parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(msgDetail prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code msgProtocol.msgDetail}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:msgProtocol.msgDetail)
          msgDetailOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return MsgProtocol.internal_static_msgProtocol_msgDetail_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return MsgProtocol.internal_static_msgProtocol_msgDetail_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  msgDetail.class, Builder.class);
        }

        // Construct using MsgProtocol.msgProtocol.msgDetail.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          type_ = 0;

          msgName_ = "";

          msgStream_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return MsgProtocol.internal_static_msgProtocol_msgDetail_descriptor;
        }

        public msgDetail getDefaultInstanceForType() {
          return msgDetail.getDefaultInstance();
        }

        public msgDetail build() {
          msgDetail result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public msgDetail buildPartial() {
          msgDetail result = new msgDetail(this);
          result.type_ = type_;
          result.msgName_ = msgName_;
          result.msgStream_ = msgStream_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof msgDetail) {
            return mergeFrom((msgDetail)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(msgDetail other) {
          if (other == msgDetail.getDefaultInstance()) return this;
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          if (!other.getMsgName().isEmpty()) {
            msgName_ = other.msgName_;
            onChanged();
          }
          if (other.getMsgStream() != com.google.protobuf.ByteString.EMPTY) {
            setMsgStream(other.getMsgStream());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          msgDetail parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (msgDetail) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.msgProtocol.msgType Type = 1;</code>
         */
        public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.msgProtocol.msgType Type = 1;</code>
         */
        public Builder setTypeValue(int value) {
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.msgProtocol.msgType Type = 1;</code>
         */
        public msgType getType() {
          msgType result = msgType.valueOf(type_);
          return result == null ? msgType.UNRECOGNIZED : result;
        }
        /**
         * <code>.msgProtocol.msgType Type = 1;</code>
         */
        public Builder setType(msgType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.msgProtocol.msgType Type = 1;</code>
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }

        private Object msgName_ = "";
        /**
         * <code>string msgName = 2;</code>
         */
        public String getMsgName() {
          Object ref = msgName_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            msgName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string msgName = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMsgNameBytes() {
          Object ref = msgName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            msgName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string msgName = 2;</code>
         */
        public Builder setMsgName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          msgName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string msgName = 2;</code>
         */
        public Builder clearMsgName() {
          
          msgName_ = getDefaultInstance().getMsgName();
          onChanged();
          return this;
        }
        /**
         * <code>string msgName = 2;</code>
         */
        public Builder setMsgNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          msgName_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString msgStream_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes msgStream = 3;</code>
         */
        public com.google.protobuf.ByteString getMsgStream() {
          return msgStream_;
        }
        /**
         * <code>bytes msgStream = 3;</code>
         */
        public Builder setMsgStream(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          msgStream_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes msgStream = 3;</code>
         */
        public Builder clearMsgStream() {
          
          msgStream_ = getDefaultInstance().getMsgStream();
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:msgProtocol.msgDetail)
      }

      // @@protoc_insertion_point(class_scope:msgProtocol.msgDetail)
      private static final msgDetail DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new msgDetail();
      }

      public static msgDetail getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<msgDetail>
          PARSER = new com.google.protobuf.AbstractParser<msgDetail>() {
        public msgDetail parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new msgDetail(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<msgDetail> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<msgDetail> getParserForType() {
        return PARSER;
      }

      public msgDetail getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private volatile Object time_;
    /**
     * <pre>
     *要第一个set
     * </pre>
     *
     * <code>string time = 1;</code>
     */
    public String getTime() {
      Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *要第一个set
     * </pre>
     *
     * <code>string time = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <code>int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int FROMWHOM_FIELD_NUMBER = 3;
    private volatile Object fromWhom_;
    /**
     * <code>string fromWhom = 3;</code>
     */
    public String getFromWhom() {
      Object ref = fromWhom_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromWhom_ = s;
        return s;
      }
    }
    /**
     * <code>string fromWhom = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromWhomBytes() {
      Object ref = fromWhom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromWhom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOWHOM_FIELD_NUMBER = 4;
    private volatile Object toWhom_;
    /**
     * <code>string toWhom = 4;</code>
     */
    public String getToWhom() {
      Object ref = toWhom_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toWhom_ = s;
        return s;
      }
    }
    /**
     * <code>string toWhom = 4;</code>
     */
    public com.google.protobuf.ByteString
        getToWhomBytes() {
      Object ref = toWhom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toWhom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>.msgProtocol.Type type = 5;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.msgProtocol.Type type = 5;</code>
     */
    public Type getType() {
      Type result = Type.valueOf(type_);
      return result == null ? Type.UNRECOGNIZED : result;
    }

    public static final int MSGD_FIELD_NUMBER = 6;
    private java.util.List<msgDetail> msgD_;
    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    public java.util.List<msgDetail> getMsgDList() {
      return msgD_;
    }
    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    public java.util.List<? extends msgDetailOrBuilder>
        getMsgDOrBuilderList() {
      return msgD_;
    }
    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    public int getMsgDCount() {
      return msgD_.size();
    }
    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    public msgDetail getMsgD(int index) {
      return msgD_.get(index);
    }
    /**
     * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
     */
    public msgDetailOrBuilder getMsgDOrBuilder(
        int index) {
      return msgD_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, time_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (!getFromWhomBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromWhom_);
      }
      if (!getToWhomBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toWhom_);
      }
      if (type_ != Type.MOMENT.getNumber()) {
        output.writeEnum(5, type_);
      }
      for (int i = 0; i < msgD_.size(); i++) {
        output.writeMessage(6, msgD_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, time_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (!getFromWhomBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromWhom_);
      }
      if (!getToWhomBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toWhom_);
      }
      if (type_ != Type.MOMENT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      for (int i = 0; i < msgD_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, msgD_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof msgProtocol)) {
        return super.equals(obj);
      }
      msgProtocol other = (msgProtocol) obj;

      boolean result = true;
      result = result && getTime()
          .equals(other.getTime());
      result = result && (getId()
          == other.getId());
      result = result && getFromWhom()
          .equals(other.getFromWhom());
      result = result && getToWhom()
          .equals(other.getToWhom());
      result = result && type_ == other.type_;
      result = result && getMsgDList()
          .equals(other.getMsgDList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + FROMWHOM_FIELD_NUMBER;
      hash = (53 * hash) + getFromWhom().hashCode();
      hash = (37 * hash) + TOWHOM_FIELD_NUMBER;
      hash = (53 * hash) + getToWhom().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getMsgDCount() > 0) {
        hash = (37 * hash) + MSGD_FIELD_NUMBER;
        hash = (53 * hash) + getMsgDList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static msgProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static msgProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static msgProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static msgProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static msgProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static msgProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static msgProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static msgProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static msgProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static msgProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static msgProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static msgProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(msgProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msgProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msgProtocol)
        msgProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgProtocol.internal_static_msgProtocol_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgProtocol.internal_static_msgProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                msgProtocol.class, Builder.class);
      }

      // Construct using MsgProtocol.msgProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMsgDFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        time_ = "";

        id_ = 0L;

        fromWhom_ = "";

        toWhom_ = "";

        type_ = 0;

        if (msgDBuilder_ == null) {
          msgD_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          msgDBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgProtocol.internal_static_msgProtocol_descriptor;
      }

      public msgProtocol getDefaultInstanceForType() {
        return msgProtocol.getDefaultInstance();
      }

      public msgProtocol build() {
        msgProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public msgProtocol buildPartial() {
        msgProtocol result = new msgProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.time_ = time_;
        result.id_ = id_;
        result.fromWhom_ = fromWhom_;
        result.toWhom_ = toWhom_;
        result.type_ = type_;
        if (msgDBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            msgD_ = java.util.Collections.unmodifiableList(msgD_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.msgD_ = msgD_;
        } else {
          result.msgD_ = msgDBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof msgProtocol) {
          return mergeFrom((msgProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(msgProtocol other) {
        if (other == msgProtocol.getDefaultInstance()) return this;
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          onChanged();
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getFromWhom().isEmpty()) {
          fromWhom_ = other.fromWhom_;
          onChanged();
        }
        if (!other.getToWhom().isEmpty()) {
          toWhom_ = other.toWhom_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (msgDBuilder_ == null) {
          if (!other.msgD_.isEmpty()) {
            if (msgD_.isEmpty()) {
              msgD_ = other.msgD_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureMsgDIsMutable();
              msgD_.addAll(other.msgD_);
            }
            onChanged();
          }
        } else {
          if (!other.msgD_.isEmpty()) {
            if (msgDBuilder_.isEmpty()) {
              msgDBuilder_.dispose();
              msgDBuilder_ = null;
              msgD_ = other.msgD_;
              bitField0_ = (bitField0_ & ~0x00000020);
              msgDBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMsgDFieldBuilder() : null;
            } else {
              msgDBuilder_.addAllMessages(other.msgD_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        msgProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (msgProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object time_ = "";
      /**
       * <pre>
       *要第一个set
       * </pre>
       *
       * <code>string time = 1;</code>
       */
      public String getTime() {
        Object ref = time_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *要第一个set
       * </pre>
       *
       * <code>string time = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *要第一个set
       * </pre>
       *
       * <code>string time = 1;</code>
       */
      public Builder setTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要第一个set
       * </pre>
       *
       * <code>string time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *要第一个set
       * </pre>
       *
       * <code>string time = 1;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        time_ = value;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 2;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object fromWhom_ = "";
      /**
       * <code>string fromWhom = 3;</code>
       */
      public String getFromWhom() {
        Object ref = fromWhom_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromWhom_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string fromWhom = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromWhomBytes() {
        Object ref = fromWhom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromWhom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromWhom = 3;</code>
       */
      public Builder setFromWhom(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromWhom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fromWhom = 3;</code>
       */
      public Builder clearFromWhom() {
        
        fromWhom_ = getDefaultInstance().getFromWhom();
        onChanged();
        return this;
      }
      /**
       * <code>string fromWhom = 3;</code>
       */
      public Builder setFromWhomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromWhom_ = value;
        onChanged();
        return this;
      }

      private Object toWhom_ = "";
      /**
       * <code>string toWhom = 4;</code>
       */
      public String getToWhom() {
        Object ref = toWhom_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toWhom_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string toWhom = 4;</code>
       */
      public com.google.protobuf.ByteString
          getToWhomBytes() {
        Object ref = toWhom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toWhom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toWhom = 4;</code>
       */
      public Builder setToWhom(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toWhom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string toWhom = 4;</code>
       */
      public Builder clearToWhom() {
        
        toWhom_ = getDefaultInstance().getToWhom();
        onChanged();
        return this;
      }
      /**
       * <code>string toWhom = 4;</code>
       */
      public Builder setToWhomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toWhom_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.msgProtocol.Type type = 5;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.msgProtocol.Type type = 5;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.msgProtocol.Type type = 5;</code>
       */
      public Type getType() {
        Type result = Type.valueOf(type_);
        return result == null ? Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.msgProtocol.Type type = 5;</code>
       */
      public Builder setType(Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.msgProtocol.Type type = 5;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<msgDetail> msgD_ =
        java.util.Collections.emptyList();
      private void ensureMsgDIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          msgD_ = new java.util.ArrayList<msgDetail>(msgD_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          msgDetail, msgDetail.Builder, msgDetailOrBuilder> msgDBuilder_;

      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public java.util.List<msgDetail> getMsgDList() {
        if (msgDBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msgD_);
        } else {
          return msgDBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public int getMsgDCount() {
        if (msgDBuilder_ == null) {
          return msgD_.size();
        } else {
          return msgDBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public msgDetail getMsgD(int index) {
        if (msgDBuilder_ == null) {
          return msgD_.get(index);
        } else {
          return msgDBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public Builder setMsgD(
          int index, msgDetail value) {
        if (msgDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgDIsMutable();
          msgD_.set(index, value);
          onChanged();
        } else {
          msgDBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public Builder setMsgD(
          int index, msgDetail.Builder builderForValue) {
        if (msgDBuilder_ == null) {
          ensureMsgDIsMutable();
          msgD_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgDBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public Builder addMsgD(msgDetail value) {
        if (msgDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgDIsMutable();
          msgD_.add(value);
          onChanged();
        } else {
          msgDBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public Builder addMsgD(
          int index, msgDetail value) {
        if (msgDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgDIsMutable();
          msgD_.add(index, value);
          onChanged();
        } else {
          msgDBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public Builder addMsgD(
          msgDetail.Builder builderForValue) {
        if (msgDBuilder_ == null) {
          ensureMsgDIsMutable();
          msgD_.add(builderForValue.build());
          onChanged();
        } else {
          msgDBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public Builder addMsgD(
          int index, msgDetail.Builder builderForValue) {
        if (msgDBuilder_ == null) {
          ensureMsgDIsMutable();
          msgD_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgDBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public Builder addAllMsgD(
          Iterable<? extends msgDetail> values) {
        if (msgDBuilder_ == null) {
          ensureMsgDIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, msgD_);
          onChanged();
        } else {
          msgDBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public Builder clearMsgD() {
        if (msgDBuilder_ == null) {
          msgD_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          msgDBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public Builder removeMsgD(int index) {
        if (msgDBuilder_ == null) {
          ensureMsgDIsMutable();
          msgD_.remove(index);
          onChanged();
        } else {
          msgDBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public msgDetail.Builder getMsgDBuilder(
          int index) {
        return getMsgDFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public msgDetailOrBuilder getMsgDOrBuilder(
          int index) {
        if (msgDBuilder_ == null) {
          return msgD_.get(index);  } else {
          return msgDBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public java.util.List<? extends msgDetailOrBuilder>
           getMsgDOrBuilderList() {
        if (msgDBuilder_ != null) {
          return msgDBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msgD_);
        }
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public msgDetail.Builder addMsgDBuilder() {
        return getMsgDFieldBuilder().addBuilder(
            msgDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public msgDetail.Builder addMsgDBuilder(
          int index) {
        return getMsgDFieldBuilder().addBuilder(
            index, msgDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .msgProtocol.msgDetail msgD = 6;</code>
       */
      public java.util.List<msgDetail.Builder>
           getMsgDBuilderList() {
        return getMsgDFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          msgDetail, msgDetail.Builder, msgDetailOrBuilder>
          getMsgDFieldBuilder() {
        if (msgDBuilder_ == null) {
          msgDBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              msgDetail, msgDetail.Builder, msgDetailOrBuilder>(
                  msgD_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          msgD_ = null;
        }
        return msgDBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msgProtocol)
    }

    // @@protoc_insertion_point(class_scope:msgProtocol)
    private static final msgProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new msgProtocol();
    }

    public static msgProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msgProtocol>
        PARSER = new com.google.protobuf.AbstractParser<msgProtocol>() {
      public msgProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msgProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<msgProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<msgProtocol> getParserForType() {
      return PARSER;
    }

    public msgProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msgProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msgProtocol_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msgProtocol_msgDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msgProtocol_msgDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021msgProtocol.proto\"\276\002\n\013msgProtocol\022\014\n\004t" +
      "ime\030\001 \001(\t\022\n\n\002id\030\002 \001(\003\022\020\n\010fromWhom\030\003 \001(\t\022" +
      "\016\n\006toWhom\030\004 \001(\t\022\037\n\004type\030\005 \001(\0162\021.msgProto" +
      "col.Type\022$\n\004msgD\030\006 \003(\0132\026.msgProtocol.msg" +
      "Detail\032S\n\tmsgDetail\022\"\n\004Type\030\001 \001(\0162\024.msgP" +
      "rotocol.msgType\022\017\n\007msgName\030\002 \001(\t\022\021\n\tmsgS" +
      "tream\030\003 \001(\014\"7\n\004Type\022\n\n\006MOMENT\020\000\022\013\n\007COMME" +
      "NT\020\001\022\n\n\006FUNREQ\020\002\022\n\n\006OTHERS\020\003\"\036\n\007msgType\022" +
      "\010\n\004TEXT\020\000\022\t\n\005IMAGE\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_msgProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msgProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msgProtocol_descriptor,
        new String[] { "Time", "Id", "FromWhom", "ToWhom", "Type", "MsgD", });
    internal_static_msgProtocol_msgDetail_descriptor =
      internal_static_msgProtocol_descriptor.getNestedTypes().get(0);
    internal_static_msgProtocol_msgDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msgProtocol_msgDetail_descriptor,
        new String[] { "Type", "MsgName", "MsgStream", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
